version: '3.5'

services:
  db:
    container_name: db
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: restaurant
    image: postgres:14.3-alpine